name: Swift

on:
  push:
    branches: [ master, Dev ]
  pull_request:
    branches: [ master, Dev ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.0,name=iPhone XS']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          xcodebuild clean test -project Pinny-iOS.xcodeproj -scheme Pinny-iOS -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}

# jobs:
#   build:

#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
